### ISSUE TITLE
Failed to resolve 'mlflow.a100.int.allencell.org'

### ISSUE THREAD

**Issue by KartikeyKansal1** [AllenCellModeling/cyto-dl#312]
macOS Sonoma, Python 3.10.13

I'm trying to run the labelfree.yaml file without any overrides using the example data and I keep running into this error:

`[2023-12-06 12:04:17,634][urllib3.connectionpool][WARNING] - Retrying (Retry(total=4, connect=4, read=5, redirect=5, status=5)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f99b99624a0>: Failed to resolve 'mlflow.a100.int.allencell.org' ([Errno 8] nodename nor servname provided, or not known)")': /api/2.0/mlflow/experiments/get-by-name?experiment_name=YOUR_EXP_NAME`

` raise MlflowException(f"API request to {url} failed with exception {e}")
mlflow.exceptions.MlflowException: API request to https://mlflow.a100.int.allencell.org/api/2.0/mlflow/experiments/get-by-name failed with exception HTTPSConnectionPool(host='mlflow.a100.int.allencell.org', port=443): Max retries exceeded with url: /api/2.0/mlflow/experiments/get-by-name?experiment_name=YOUR_EXP_NAME (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f99b9960a90>: Failed to resolve 'mlflow.a100.int.allencell.org' ([Errno 8] nodename nor servname provided, or not known)"))`

tried:  `ping mlflow.a100.int.allencell.org` 
Output: `ping: cannot resolve mlflow.a100.int.allencell.org: Unknown host`

How to resolve this issue? I already have all the necessary dependencies from the requirements file. Also tried overriding the `experiment_name=example`, throws the same error.

**Comment by benjijamorris** [comment]
Hi @KartikeyKansal1, thanks for the issue. I'll update the default configs, but in the meantime you can add `logger=csv` to your training command (i.e. `python cyto_dl/train.py experiment=im2im/segmentation logger=csv`. Let me know if you have other questions or run into any issues!
