### ISSUE TITLE
Unable to train ~>100 epochs

### ISSUE THREAD

**Issue by KartikeyKansal1** [AllenCellModeling/cyto-dl#373]
Hi, I'm running python cyto_dl/train.py experiment=im2im/labelfree but the training stops roughly after 100 epochs even when I set the trainer.max_epochs to be way higher. I tried restarting the training from the last epoch but it stopped again after running just 1 more epoch. Doesn't throw out any error either. Any suggestions?

**Comment by benjijamorris** [comment]
Hey @KartikeyKansal1! Are you using the Early Stopping Callback? If your loss is plateauing and you're using early stopping, training will end before `trainer.max_epochs`. One other thing to check is if you have `trainer.detect_anomaly=True`, any nan grad will stop training.

**Comment by KartikeyKansal1** [comment]
Gotcha, yes I was using the early stopping callback. Thanks!
